### ISSUE TITLE
Is this community active?

### ISSUE THREAD

**Issue by ekhabarov** [nodeschool/moscow#5]

**Comment by rickheere** [comment]
It is.

**Comment by ekhabarov** [comment]
@rickheere someone plan to organize any events? I ask because I didn't found any info about this events.

**Comment by rickheere** [comment]
See http://nodeschool.io/events.html for upcoming events

**Comment by AVVS** [comment]
Everybody is quite busy :) I'm personally planning to do a small event during geek week in mid November

**Comment by ekhabarov** [comment]
Great! I'll be there!  Thanks!
